# Generated by Django 2.0.1 on 2020-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200426_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='employed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='installments',
            field=models.CharField(choices=[('upfront', 'Upfront'), ('installments', 'Installments')], default='no', max_length=100),
        ),
    ]
