# Generated by Django 2.0.1 on 2020-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200529_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
