# Generated by Django 2.0.1 on 2020-06-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200620_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_day',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact_time',
        ),
    ]
