# Generated by Django 2.0.1 on 2020-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200622_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='monday', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=100),
        ),
    ]
